name: Hostname and Configurations Test

on:
  push:
    branches:
      - main

jobs:
  test_hostname_and_configurations:
    runs-on: [ubuntu-latest, my-required-runner-config]
    steps:
      - name: Display hostname
        run: hostname

      - name: Display system information
        run: |
          echo "Operating System:"
          cat /etc/os-release
          echo "Memory Information:"
          free -m
